### ISSUE TITLE
apt-get-simulate-update blocks system apt

### ISSUE THREAD

**Issue by derlaft** [Whonix/anon-shared-helper-scripts#2]
Steps to reproduce:

1) Install some .deb without it dependencies using dpkg (i.e. "break" system)
2) Try to do apt-get install -f: /usr/lib/anon-shared-helper-scripts/apt-get-update-simulate will be contantly relaunched, locking /var/lib/dpkg/lock and preventing system apt-get to run

**Comment by adrelanos** [comment]
Alexey Derlaft:
> Steps to reproduce:
> 
> 1) Install some deb without it dependencies using dpkg (ie "break" system)

Using dpkg --force?

Maybe the simpler way to reproduce is just starting the installation of
some random package.

sudo apt-get install tetgen

Then not answer in the console. Just keep it running. Package database
will be locked.

Then start whonixcheck. Or whonixcheck --debug.

It certainly keep locking because it will be continuously checking.
Until you terminate whonixcheck.

Is that what you mean?

> 2) Try to do apt-get install -f: /usr/lib/anon-shared-helper-scripts/apt-get-update-simulate will be contantly relaunched, locking /var/lib/dpkg/lock and preventing system apt-get to run

Do you think it's a problem with apt-get-update-simulate? Currently it's
only user is whonixcheck (which autostarts). The simplified flow is the
following.

whonixcheck
-> /usr/lib/whonixcheck/check_package_manager_running.bsh
-> check_package_manager_running_helper
-> /usr/lib/anon-shared-helper-scripts/apt-get-update-simulate

**Comment by adrelanos** [comment]
Ping @derlaft?

**Comment by derlaft** [comment]
@adrelanos hello. Sorry, I don't quite remember what happened, why I haven't answered and how I resolved it.

**Comment by adrelanos** [comment]
Thanks!
